# Data Containers

tmpdata:
  image: busybox:latest
  volumes:
    - /home/.cos
    - /log
    - /etc/uwsgi
    - /tmp


# Service Containers

postgres:
  image: centerforopenscience/postgres:9.4
  expose:
    - 5432
  volumes_from:
    - tmpdata


# Server Containers

web:
  # image: centerforopenscience/dor:latest
  build: .
  environment:
    # - SOURCE_BRANCH=develop
    # - SOURCE_REPO=https://github.com/mfraezz/DirectoryOfRepositories.git
    - SOURCE_BRANCH=feature/production
    - SOURCE_REPO=https://github.com/icereval/DirectoryOfRepositories.git
  ports:
    - 8000:8000
  expose:
    - 8000
  links:
    - postgres:postgres
  volumes_from:
    - tmpdata
