nginx:
#  image: nginx
  build: .
#  command: [nginx-debug, '-g', 'daemon off;']
  volumes:
   - ./files/conf/nginx.conf:/etc/nginx/nginx.conf
   - ./files/conf/conf.d/site.conf:/etc/nginx/conf.d/site.conf
   - ./files/modsec_includes.conf:/usr/local/nginx/conf/modsec_includes.conf
   - ./files/modsecurity.conf:/usr/local/nginx/conf/modsecurity.conf
   - ./files/crs-setup.conf:/usr/local/nginx/conf/rules/crs-setup.conf
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
  ports:
    - 8000:80
  expose:
    - 8000
