
# Storage Containers

# storage:
#   image: busybox:latest
#   volumes:
#     - /tmp
#     - /code
#     - /data/db


# # Service Containers

 rabbitmq:
   image: rabbitmq:latest

elasticsearch:
  image: elasticsearch:latest

tokumx:
  image: centerforopenscience/tokumx:latest
  environment:
    - TOKU_HUGE_PAGES_OK=1


# Server Containers


# cas:
#   image: centerforopenscience/cas:4.1
#   ports:
#     - 8080:8080
#     - 8443:8443

api:
  tty: true
  # build: ./api
  image: centerforopenscience/osf:api
  # command: invoke apiserver --host 0.0.0.0 --port 8000
  environment:
     - SOURCE_BRANCH=develop
     - SOURCE_REPO=https://github.com/CenterForOpenScience/osf.io.git
     - UPDATE_CMD=invoke wheelhouse --dev --addons && invoke requirements --dev --addons && gosu www-data python manage.py collectstatic --noinput
  expose:
    - 8000
  ports:
    - 8000:8000
  links:
    - tokumx:tokumx
    - elasticsearch:elasticsearch
    - rabbitmq:rabbitmq
  volumes:
    - ./settings/local-docker.py:/code/website/settings/local.py
  # volumes_from:
  #   - storage

# sharejs:
#   build: ./sharejs
#   command: invoke sharejs
#   environment:
#     # - SOURCE_BRANCH=develop
#     - SOURCE_REPO=https://github.com/CenterForOpenScience/osf.io.git
#     - SHAREJS_SERVER_HOST=0.0.0.0
#     - SHAREJS_SERVER_PORT=7007
#     - SHAREJS_CORS_ALLOW_ORIGIN=http://localhost:5000
#     - SHAREJS_DB_HOST=tokumx
#     - SHAREJS_DB_PORT=27017
#     - SHAREJS_DB_NAME=sharejs
#     - SHAREJS_DEBUG=false
#   expose:
#     - 7007
#   ports:
#     - 7007:7007
#   links:
#     - tokumx:tokumx

web:
  tty: true
  # build: ./web
  image: centerforopenscience/osf:web
  command: invoke server --host 0.0.0.0 --port 5000
  environment:
     - SOURCE_BRANCH=develop
     - SOURCE_REPO=https://github.com/CenterForOpenScience/osf.io.git
     - UPDATE_CMD=invoke wheelhouse --dev --addons && invoke requirements --dev --addons && gosu www-data invoke assets --dev
  expose:
    - 5000
  ports:
    - 5000:5000
  links:
    - tokumx:tokumx
    - elasticsearch:elasticsearch
    - rabbitmq:rabbitmq
  volumes:
    - ./settings/local-docker.py:/code/website/settings/local.py
  # volumes_from:
  #   - storage

# celery:
#   build: ./server
#   command: 'invoke celery_worker'
#   environment:
#     - SOURCE_BRANCH=develop
#     - SOURCE_REPO=https://github.com/CenterForOpenScience/osf.io.git
#     - UPDATE_CMD="invoke requirements --dev --addons"
#   links:
#     - rabbitmq:rabbitmq
#     - tokumx:tokumx
##   volumes_from:
##     - storage

# celery:
#   build: ./server
#   command: 'invoke celery_beat'
#   environment:
#     - SOURCE_BRANCH=develop
#     - SOURCE_REPO=https://github.com/CenterForOpenScience/osf.io.git
#   links:
#     - rabbitmq:rabbitmq
#     - tokumx:tokumx
##   volumes_from:
##     - storage
